version: '3.7'

services:
  grafana:
    build: ${PWD}/grafana
    container_name: grafana
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning:ro
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"

  influxdb:
    build: ${PWD}/influxdb
    container_name: influxdb
    restart: always
    command: "-config /etc/influxdb/influxdb.conf"
    environment: 
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    volumes:
      - ${PWD}/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb-data:/var/lib/influxdb

  telegraf:
    build: ${PWD}/telegraf
    container_name: telegraf
    volumes:
      - ${PWD}/telegraf/conf:/etc/telegraf

volumes: 
  influxdb-data:
  grafana-data: